### ISSUE TITLE
Labyrinth events

### ISSUE THREAD

**Issue by Voxelslide** [TrinityUniversityGameDesign/advgamedev-s23-intothefire#12]
- [ ] Design PCG system
- [x] Timer system
- [x] Global hazards
- [ ] Points of interest/ objectives

- [ ] Spleef Side Event #36 
- [ ] Mini-Boss Side Event #37 
- [ ] Team Hunt Side Event #38 
- [ ] Skirmish Side Event #39 
- [ ] Scavenger Hunt Major Event #42 
- [ ] Roaming Boss Major Event #43 
- [x] Meteor Micro Event
